### ISSUE TITLE
Error processing dependency package.json files

### ISSUE THREAD

**Issue by MMJM** [aurelia/webpack-plugin#12]
I have a project that is using PouchDB and this does not seem to play well with the aurelia-webpack-plugin. 

```
 65% 101/110 build modulespath.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received { './lib/extras/ajax.js': './lib/extras/ajax-browser.js',
  './lib/extras/checkpointer.js': './lib/extras/checkpointer-browser.js',
  './lib/extras/generateReplicationId.js': './lib/extras/generateReplicationId-browser.js',
  './lib/index.js': './lib/index-browser.js',
  crypto: false,
  fs: false,
  leveldown: false }
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at /Users/johnmooney/Dev/MMPOC/node_modules/aurelia-webpack-plugin/index.js:22:35
    at Array.forEach (native)
    at getContextMap (/Users/johnmooney/Dev/MMPOC/node_modules/aurelia-webpack-plugin/index.js:15:18)
    at AureliaWebpackPlugin.<anonymous> (/Users/johnmooney/Dev/MMPOC/node_modules/aurelia-webpack-plugin/index.js:56:29)
    at /Users/johnmooney/Dev/MMPOC/node_modules/aurelia-webpack-plugin/index.js:90:7
    at /Users/johnmooney/Dev/MMPOC/node_modules/webpack/lib/ContextModuleFactory.js:124:5
    at /Users/johnmooney/Dev/MMPOC/node_modules/async/lib/async.js:52:16
    at /Users/johnmooney/Dev/MMPOC/node_modules/async/lib/async.js:361:13
```

What appears to be happening is that the plugin is processing the PouchDB package.json file and within that it is processing the browser section and throwing the error. 

```
"browser": {
    "./lib/extras/ajax.js": "./lib/extras/ajax-browser.js",
    "./lib/extras/checkpointer.js": "./lib/extras/checkpointer-browser.js",
    "./lib/extras/generateReplicationId.js": "./lib/extras/generateReplicationId-browser.js",
    "./lib/index.js": "./lib/index-browser.js",
    "crypto": false,
    "fs": false,
    "leveldown": false
  },
```

I'm no expert on webpack.

Why is the plugin processing this file?

The PouchDB team did some work to make PouchDB work with webpack and as far as I know they use rollup to bundle their stuff in to js files for webpack. I don't know why the plugin isn't including the dist folder instead.

**Comment by wesleyb-io** [comment]
I have come across another example of Aurelia's webpack plugin parsing a thrid-party's `package.json` `browser` property, and then exploding.

Webpack Plugin Code: [aurelia/webpack-plugin @ 0.1.0 — index.js — line 35](https://github.com/aurelia/webpack-plugin/blob/0.1.0/index.js#L35)
Third-Party Package: [nodeca/js-yaml @ 3.5.5, 3.5.3, 3.4.3 — package.json — line 44](https://github.com/nodeca/js-yaml/blob/3.5.5/package.json#L44)

```bash
> webpack -p --config webpack.prod.config.js --progress --devtool source-map --bail

 57% 8/10 build modulespath.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received { buffer: false }
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at /my/code/node_modules/aurelia-webpack-plugin/index.js:42:39
    at Array.forEach (native)
    at AureliaWebpackPlugin.<anonymous> (/my/code/node_modules/aurelia-webpack-plugin/index.js:28:22)
    at /my/code/node_modules/aurelia-webpack-plugin/index.js:79:7
    at /my/code/node_modules/webpack/lib/ContextModuleFactory.js:124:5
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:361:13
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/my/code/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:358:17
    at /my/code/node_modules/webpack/lib/ContextModuleFactory.js:124:5
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:361:13
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/my/code/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:358:17
    at /my/code/node_modules/webpack/lib/ContextModuleFactory.js:124:5
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:361:13
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/my/code/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /my/code/node_modules/webpack/node_modules/async/lib/async.js:358:17
    at /my/code/node_modules/webpack/lib/ContextModuleFactory.js:112:8
    at ContextModuleFactory.<anonymous> (/my/code/node_modules/webpack/node_modules/tapable/lib/Tapable.js:82:11)
    at ContextModuleFactory.<anonymous> (/my/code/node_modules/webpack/lib/dependencies/RequireContextPlugin.js:50:4)
```

**Comment by masterpoi** [comment]
Same thing with mapbox-gl

**Comment by EisenbergEffect** [comment]
There are two related issues that were closed. Is this now resolved? If not, please advise or submit a PR to help us address the issue.

**Comment by masterpoi** [comment]
This specific issue is resolved when loading mapbox-gl. (There are still other issues, unrelated to aurelia, but they are being tracked here: https://github.com/mapbox/mapbox-gl-js/issues/1649)

**Comment by EisenbergEffect** [comment]
Thanks. I'm going to close this. We've had some fixes in this area.
