### ISSUE TITLE
[Webpack 5] Module Federation plugin does not work

### ISSUE THREAD

**Issue by damian131** [aurelia/webpack-plugin#186]
**I'm submitting a bug report**

* **Library Version:**
5.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.18.1

* **NPM Version:**
6.13.4

* **JSPM OR Webpack AND Version**
webpack 5.42.0

* **Browser:**
Chrome 91.0.4472.124 (Official Build) (64-bit)

* **Language:**
TypeScript 4.2.4

**Current behavior:**
Once configuring Webpack Federation Module for two Aurelia projects (one is a host and another one is a remote component), the host is not requesting for `remoteEntry.js` from the remote component.

Both of the projects have a clean setup built using `au new` and they are migrated to Webpack 5.

Host's Module Federation plugin config:
![image](https://user-images.githubusercontent.com/6074920/125778649-563646ed-2d1b-49ed-b2e5-905977f6f24f.png)

Remote Component's Module Federation plugin config:
![image](https://user-images.githubusercontent.com/6074920/125778699-9ff6d92b-9b16-466d-bce0-71657f852d39.png)

Remote Component's function definition:
![image](https://user-images.githubusercontent.com/6074920/125778839-2711ceec-d484-46d5-b241-361f38820888.png)

Host using Remote Component's function:
![image](https://user-images.githubusercontent.com/6074920/125778919-96bca33b-120b-4078-938b-a335c059a4b9.png)

Build has succeeded, but the issue occurs during runtime. `remoteEntry.js` is not issued by the host:
![image](https://user-images.githubusercontent.com/6074920/125779546-c3717810-35b9-4d73-9250-45703fe7bdfb.png)

However it has been successfully generated on the remote component side:
![image](https://user-images.githubusercontent.com/6074920/125779871-f1c142bc-b376-4ce0-befd-3b6b2f4c82d9.png)

**Expected/desired behavior:**
`remoteEntry.js` file is requested by the host which eventually ends up with remote component's function being called on the host side.

**What is the motivation / use case for changing the behavior?**
Having ability to use Module Federation plugin within Aurelia apps and taking advantage from micro-frontend architecture.

**Comment by bigopon** [comment]
@damian131 thanks, I'll have a look

**Comment by bigopon** [comment]
@damian131 I've been able to setup a simple a project with 2 apps connected through module defederation here https://github.com/bigopon/example-au-module-federation

Can you have a try?

`m` property in the `App` is a promise of loading the module at `app2`, so just need to `.then(m => m.superFunction()` to see some console logging.

**Comment by bigopon** [comment]
@damian131 forgot to mention that I built the apps independently and run via `http-server`:
app2: port 8080
app1: any port

**Comment by damian131** [comment]
Hi @bigopon, thank you so much for taking a look.

Indeed, when trying to import it in this way it is working. What is the reasoning behind that?

Additionally, I've tried to import a remote Aurelia's component to the host and I'm getting:
![obraz](https://user-images.githubusercontent.com/6074920/126880527-43a84343-3cfe-40ed-ab95-549b08ac1bd5.png)

Any idea how to make it working?

Code: https://github.com/damian131/example-au-module-federation

**Comment by damian131** [comment]
Hi @bigopon, did you have a chance to look at this?

**Comment by bigopon** [comment]
Oops, I forgot about this. Will do soon @damian131

**Comment by damian131** [comment]
Hi @bigopon, sorry for pinging you once again on this - did you have a chance to take a look?

**Comment by bigopon** [comment]
@damian131 I haven't had a chance yet, but have been keeping a note of this in my mind for whole this week since I recently checked on it for a blog. Will do this weekend.

**Comment by bigopon** [comment]
I've been able to reproduce the issue, a workaround is to export `hello` from `superFunction`:
```ts
export const hello = () => import('./hello/hello');
```
then in usage, we can do
```ts
p = import ('app2/hello').then(m => m()).then(m => m.Hello)
```

**Comment by ItWorksOnMyMachine** [comment]
How would we expose an actual component, a view and viewModel, that renders itself.  Basically, taking the example app1 and app2, how would we go about exposing app2's App component to app1 and rendering it on the screen?

**Comment by KayvandenHeuvel** [comment]
> How would we expose an actual component, a view and viewModel, that renders itself? Basically, taking the example app1 and app2, how would we go about exposing app2's App component to app1 and rendering it on the screen?
> 
> I have updated app2's webpack.config.js file to this:
> 
> ```
> new ModuleFederationPlugin({
>       name: 'app2',
>       filename: 'remoteEntry.js',
>       exposes: {
>         './superFunction': './src/superFunction',
>         './App': './src/app'
>       },
>       // shared: { react: { singleton: true }, 'react-dom': { singleton: true } }
>     }),
> ```
> 
> And I can now import the component in app1. I'm just not sure how to actually use it...

Hi, have you found out how to get this to work? We also managed to import the component in app1 but can't seem to find how to get it to render.

**Comment by KentuckyMC** [comment]
Someone got it to render in Aurelia? Still looking for an answer on this one.

**Comment by d1820** [comment]
This still does not work at all. Even with a simple hello world.

Error 1:
This happens first time through, clear the error and fire off import again, 
```
ERROR
Loading script failed.
(missing: http://localhost:9100/remoteEntry.js)
while loading "./superFunction" from webpack/container/reference/remote
ScriptExternalLoadError
    at webpack/container/reference/remote(http://localhost:9000/entry.bundle.js:311:25)
    at __webpack_require__ (http://localhost:9000/entry.bundle.js:461:32)
    at initExternal (http://localhost:9000/entry.bundle.js:735:28)
    at __webpack_require__.I (http://localhost:9000/entry.bundle.js:747:15)
    at http://localhost:9000/entry.bundle.js:1244:47
    at webpack/sharing/consume/default/aurelia/aurelia (http://localhost:9000/entry.bundle.js:1295:71)
    at __webpack_require__.m.<computed> (http://localhost:9000/entry.bundle.js:1303:54)
    at __webpack_require__ (http://localhost:9000/entry.bundle.js:461:32)
    at fn (http://localhost:9000/entry.bundle.js:818:21)
    at eval (webpack-internal:///./src/main.ts:2:65)
```

Error 2:
Once the import has been completed.
```
ERROR
m.superFunction is not a function
TypeError: m.superFunction is not a function
    at eval (webpack-internal:///./src/my-app.ts:38:65)
```
**Host:**

tsconfig
```
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "target": "ES2017",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "importHelpers": true,
    "sourceMap": true
  },
  "include": [
    "src"
  ],
  "files": [
    "src/resource.d.ts"
  ]
}
```

WebPack
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const Dotenv = require('dotenv-webpack');
const TerserPlugin = require('terser-webpack-plugin');
const { ModuleFederationPlugin } = require('webpack').container;

const cssLoader = {
  loader: 'css-loader'
};

module.exports = function(env, { analyze }) {
  const production = env.production || process.env.NODE_ENV === 'production';
  return {
    target: 'web',
    mode: production ? 'production' : 'development',
    devtool: production ? undefined : 'eval-source-map',
    optimization: {
    },
    entry: {
      entry: './src/main.ts',
    },
    output: {
      clean: true,
      path: path.resolve(__dirname, 'dist'),
      filename: production ? '[name].[contenthash].bundle.js' : '[name].bundle.js',
    },
    resolve: {
      extensions: ['.ts', '.js'],
      modules: [path.resolve(__dirname, 'src'), 'node_modules'],
    },
    devServer: {
      historyApiFallback: true,
      open: !process.env.CI,
      port: 9000
    },
    module: {
      rules: [
        { test: /\.(png|svg|jpg|jpeg|gif)$/i, type: 'asset' },
        { test: /\.(woff|woff2|ttf|eot|svg|otf)(\?v=[0-9]\.[0-9]\.[0-9])?$/i, type: 'asset' },
        { test: /\.css$/i, use: ['style-loader', cssLoader] },
        { test: /\.scss$/i, use: ['style-loader', cssLoader] },
        { test: /\.ts$/i, use: ['ts-loader', '@aurelia/webpack-loader'], exclude: /node_modules/ },
        {
          test: /[/\\]src[/\\].+\.html$/i,
          use: '@aurelia/webpack-loader',
          exclude: /node_modules/
        }
      ]
    },
    plugins: [
      new ModuleFederationPlugin({
        name: "shell",
        filename: 'remoteEntry.js',
        shared: {
          'aurelia': { singleton: true, eager: true },
        },
        remotes: {
          remote: "remote@http://localhost:9100/remoteEntry.js",
        },
      }),
      new HtmlWebpackPlugin({ template: 'index.html', favicon: 'favicon.ico' }),
    ].filter(p => p)
  };
};

function getAureliaDevAliases() {
  return [
    'aurelia',
    'fetch-client',
    'kernel',
    'metadata',
    'platform',
    'platform-browser',
    'route-recognizer',
    'router',
    'router-lite',
    'runtime',
    'runtime-html',
    'testing',
    'state',
    'ui-virtualization'
  ].reduce((map, pkg) => {
    const name = pkg === 'aurelia' ? pkg : `@aurelia/${pkg}`;
    try {
      const packageLocation = require.resolve(name);
      map[name] = path.resolve(packageLocation, `../../esm/index.dev.mjs`);
    } catch {/**/ }
    return map;
  }, {});
}
```

Package.json
```
{
  "name": "Shell",
  "description": "An Aurelia 2 client application.",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": "???"
  },
  "license": "UNLICENSED",
  "dependencies": {
  "aurelia": "2.0.0-beta.25"
  },
  "devDependencies": {
    "@aurelia/testing": "2.0.0-beta.25",
    "@aurelia/runtime-html": "2.0.0-beta.25",
    "@aurelia/webpack-loader": "2.0.0-beta.25",
    "@aurelia/ts-jest": "2.0.0-beta.25",
    "@types/jest": "29.5.12",
    "@types/node": "22.10.2",
    "@types/webpack": "5.28.5",
    "css-loader": "6.10.0",
    "dotenv-webpack": "8.1.0",
    "eslint": "9.17.0",
    "globals": "15.14.0",
    "html-webpack-plugin": "5.6.3",
    "jest": "29.7.0",
    "jest-environment-jsdom": "29.7.0",
    "jest-transform-stub": "2.0.0",
    "jsdom": "25.0.1",
    "less": "4.4.0",
    "less-loader": "12.3.0",
    "mini-css-extract-plugin": "2.8.1",
    "node-polyfill-webpack-plugin": "4.1.0",
    "style-loader": "4.0.0",
    "stylelint": "16.12.0",
    "stylelint-config-standard": "36.0.1",
    "ts-jest": "29.1.2",
    "ts-loader": "9.5.1",
    "tslib": "2.8.1",
    "typescript": "5.7.2",
    "typescript-eslint": "8.18.1",
    "webpack": "5.97.1",
    "webpack-cli": "5.1.4",
    "webpack-dev-server": "5.2.2",
    "webpack-merge": "5.10.0"
  },
  "scripts": {
    "start": "webpack serve",
  }
}
```

Invoking Code
```
export class MyApp {
  public message = 'Hello World!';

   handleClick() {
    try {
         import('MediRDispatchApp/superFunction').then(m => {
          console.log(m, m.default);
          m?.superFunction();
        });
    } catch (e) {
      console.error("Error during module import:", e);
    }
  }
}
```

**Remote:**

tsconfig
```
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "target": "ES2017",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "importHelpers": true,
    "sourceMap": true,
    "emitDecoratorMetadata": false,
    "experimentalDecorators": false,
  },
  "include": [
    "src",
    "test"
  ],
  "files": [
    "src/resource.d.ts"
  ]
}

```
Webpack
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const webpack = require('webpack');
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');
const pkg = require('./package.json');
const deps = pkg.dependencies || {};
const { ModuleFederationPlugin } = webpack.container;

function getEnvironment(env) {
  return env.production
    ? path.resolve(__dirname, 'src/environments/environment.prod.ts')
    : env.test
      ? path.resolve(__dirname, 'src/environments/environment.test.ts')
      : env.dev
        ? path.resolve(__dirname, 'src/environments/environment.dev.ts')
        : path.resolve(__dirname, 'src/environments/environment.ts');
}

const ensureArray = (config) => config && (Array.isArray(config) ? config : [config]) || [];
const when = (condition, config, negativeConfig) =>
  condition ? ensureArray(config) : ensureArray(negativeConfig);

module.exports = (env) => {
  console.log("parameters:", env);
  const production = env.production;
  const extractCss = env.extractCss;

  return {
    target: 'web',
    mode: production ? 'production' : 'development',
    devtool: production ? 'source-map' : 'eval-source-map',
    entry: {
      entry: './src/main.ts'
    },
    output: {
      uniqueName: 'remote',
      path: path.resolve(__dirname, 'dist'),
      filename: production ? '[name].[contenthash].js' : '[name].bundle.js',
      publicPath: 'auto',
      clean: true,
    },
    resolve: {
      extensions: ['.ts', '.js'],
      modules: [path.resolve(__dirname, 'src'), 'node_modules'],
      alias: {
        'environment$': getEnvironment(env),
      }
    },
    devServer: {
      headers: {
        "Access-Control-Allow-Origin": "*"
      },
      port: 9100,
      historyApiFallback: true,
      //open: true,
      hot: true,
    },
    module: {
      rules: [
        // Asset loaders
        { test: /\.(png|svg|jpg|jpeg|gif)$/i, type: 'asset' },
        { test: /\.(woff|woff2|ttf|eot|svg|otf)(\?v=[0-9]\.[0-9]\.[0-9])?$/i, type: 'asset' },
        // CSS handling
        {
          test: /\.css$/i,
          issuer: { not: /\.html$/i },
          use:
            extractCss ? [MiniCssExtractPlugin.loader, 'css-loader']
              : ['style-loader', 'css-loader'],
          exclude: /node_modules/
        },
        {
          test: /\.css$/i,
          issuer: /\.html$/i,
          // CSS required in templates cannot be extracted safely
          use: 'css-loader'
        },
        {
          test: /\.less$/i,
          use: extractCss ? [MiniCssExtractPlugin.loader, 'css-loader', 'less-loader']
            : ['style-loader', 'css-loader', 'less-loader']
        },
        // TypeScript + Aurelia loader
        {
          test: /\.ts$/i,
          use: ['ts-loader', '@aurelia/webpack-loader'],
          exclude: /node_modules/
        },
        {
          test: /[/\\]src[/\\].+\.html$/i,
          use: {
            loader: '@aurelia/webpack-loader',
            options: {
              // The other possible Shadow DOM mode is 'closed'.
              // If you turn on "closed" mode, there will be difficulty to perform e2e
              // tests (such as Playwright). Because shadowRoot is not accessible through
              // standard DOM APIs in "closed" mode.
              //defaultShadowOptions: { mode: 'open' }
            }
          },
          exclude: /node_modules/
        }
      ]
    },
    plugins: [
      ...when(extractCss, new MiniCssExtractPlugin({
        filename: production ? '[contenthash].css' : '[id].css',
      })),
      new ModuleFederationPlugin({
        name: 'remote',
        filename: 'remoteEntry.js',
        shared: {
          'aurelia': { singleton: true, eager: true, requiredVersion: '2.0.0-beta.25' },
        },
        exposes: {
          './superFunction': './src/remotes/superFunction',
        },
      }),
      //new AssignToWindowPlugin('MediRDispatchApp'),
      new HtmlWebpackPlugin({
        template: 'index.html',
        favicon: 'favicon.ico',
        minify: production ? {
          removeComments: true,
          collapseWhitespace: true
        } : undefined,
        metadata: {
          title: pkg.name,
          baseUrl: "/"
        }
      }),
      new NodePolyfillPlugin(),
      ...(production ? [new MiniCssExtractPlugin({
        filename: '[name].[contenthash].css',
        chunkFilename: '[name].[contenthash].css',
      })] : []),
    ],
    optimization: {
      runtimeChunk: 'single',
      splitChunks: {
        chunks: 'all',
      },
      minimize: production,
    },

  };
};
```

Package.json
```
{
  "name": "remote",
  "description": "remote",
  "version": "0.1.0",
  "license": "UNLICENSED",
  "scripts": {
    "start": "webpack serve --env local"
  },
  "dependencies": {
    "@aurelia/router": "2.0.0-beta.25",
    "aurelia": "2.0.0-beta.25"
  },
  "devDependencies": {
    "@aurelia/testing": "2.0.0-beta.25",
    "@aurelia/runtime-html": "2.0.0-beta.25",
    "@aurelia/webpack-loader": "2.0.0-beta.25",
    "@aurelia/ts-jest": "2.0.0-beta.25",
    "@types/jest": "29.5.12",
    "@types/node": "22.10.2",
    "@types/webpack": "5.28.5",
    "css-loader": "6.10.0",
    "dotenv-webpack": "8.1.0",
    "eslint": "9.17.0",
    "globals": "15.14.0",
    "html-webpack-plugin": "5.6.3",
    "jest": "29.7.0",
    "jest-environment-jsdom": "29.7.0",
    "jest-transform-stub": "2.0.0",
    "jsdom": "25.0.1",
    "less": "4.4.0",
    "less-loader": "12.3.0",
    "mini-css-extract-plugin": "2.8.1",
    "node-polyfill-webpack-plugin": "4.1.0",
    "style-loader": "4.0.0",
    "stylelint": "16.12.0",
    "stylelint-config-standard": "36.0.1",
    "ts-jest": "29.1.2",
    "ts-loader": "9.5.1",
    "tslib": "2.8.1",
    "typescript": "5.7.2",
    "typescript-eslint": "8.18.1",
    "webpack": "5.97.1",
    "webpack-cli": "5.1.4",
    "webpack-dev-server": "5.2.2",
    "webpack-merge": "5.10.0"
  }
}

```
Exposed Code
```
export function superFunction() {
  console.log('hello world');
}
```
