### ISSUE TITLE
Webpack build failing when adding socket.io

### ISSUE THREAD

**Issue by darryldaniel** [aurelia/webpack-plugin#22]
Hi,

I am getting the following error when trying to add socket.io to my aurelia app.

```
WARNING in ./~/socket.io-client/socket.io.js                                                                   
Critical dependencies:                                                                                         
1:475-482 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to r
equire the original source to get better results.                                                              
 @ ./~/socket.io-client/socket.io.js 1:475-482                                                                 
                                                                                                               
WARNING in ./~/ws/lib/BufferUtil.js                                                                            
Module not found: Error: Cannot resolve module 'bufferutil' in C:\workspace\Game\Snap\node_modules\ws\lib      
 @ ./~/ws/lib/BufferUtil.js 10:19-40                                                                           
                                                                                                               
WARNING in ./~/ws/lib/Validation.js                                                                            
Module not found: Error: Cannot resolve module 'utf-8-validate' in C:\workspace\Game\Snap\node_modules\ws\lib  
 @ ./~/ws/lib/Validation.js 10:19-44                                                                           
                                                                                                               
ERROR in ./~/socket.io/lib/index.js                                                                            
Module not found: Error: Cannot resolve module 'fs' in C:\workspace\Game\Snap\node_modules\socket.io\lib       
 @ ./~/socket.io/lib/index.js 7:11-24                                                                          
                                                                                                               
ERROR in ./~/socket.io/lib/index.js                                                                            
Module not found: Error: Cannot resolve module 'socket.io-client/package' in C:\workspace\Game\Snap\node_module
s\socket.io\lib                                                                                                
 @ ./~/socket.io/lib/index.js 10:20-55                                                                         
                                                                                                               
ERROR in ./~/engine.io/lib/server.js                                                                           
Module not found: Error: Cannot resolve module 'fs' in C:\workspace\Game\Snap\node_modules\engine.io\lib       
 @ ./~/engine.io/lib/server.js 8:19-32                                                                         
                                                                                                               
ERROR in ./~/ws/lib/WebSocketServer.js                                                                         
Module not found: Error: Cannot resolve module 'tls' in C:\workspace\Game\Snap\node_modules\ws\lib             
 @ ./~/ws/lib/WebSocketServer.js 15:10-24                                                                      
                                                                                                               
ERROR in ./~/options/lib/options.js                                                                            
Module not found: Error: Cannot resolve module 'fs' in C:\workspace\Game\Snap\node_modules\options\lib         
 @ ./~/options/lib/options.js 6:9-22                                                                           
                                                                                                               
ERROR in ./~/accepts/~/mime-db/db.json                                                                         
Module parse failed: C:\workspace\Game\Snap\node_modules\accepts\node_modules\mime-db\db.json Unexpected token 
(2:40)                                                                                                         
You may need an appropriate loader to handle this file type.                                                   
SyntaxError: Unexpected token (2:40)                                                                           
    at Parser.pp.raise (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:920:13)                        
    at Parser.pp.unexpected (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:1483:8)                   
    at Parser.pp.semicolon (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:1462:73)                   
    at Parser.pp.parseExpressionStatement (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:1976:8)     
    at Parser.pp.parseStatement (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:1754:188)             
    at Parser.pp.parseBlock (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:1991:21)                  
    at Parser.pp.parseStatement (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:1735:19)              
    at Parser.pp.parseTopLevel (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:1648:21)               
    at Parser.parse (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:1616:17)                          
    at Object.parse (C:\workspace\Game\Snap\node_modules\acorn\dist\acorn.js:882:44)                           
 @ ./~/accepts/~/mime-db/index.js 11:17-37                           
```                                          

 The webpack build works when I remove the aurelia plugin and I have tried adding socket.io as a submodule but it still doesnt work.

Thanks guys!

**Comment by darryldaniel** [comment]
Ok I've answered my own question. I needed to add a script loader for parsing the socket.io library:

``` { test: /\.js$/, loader: 'script-loader', include: /socket.io/ }, ```

This solved my issues.
