### ISSUE TITLE
Error processing dependency package.json files

### ISSUE THREAD

**Issue by aaronroberson** [aurelia/webpack-plugin#28]
This is a resurrection of #12 using aurelia-webpack-plugin v1.0.0-beta.1.0.4. 

When tv4 is included in package.json, the webpack plugin blows up at the tv4 package which has the following browser value:

`browser: { os: false }`

Here is the stack trace:
```
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received { os: false }
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at /Users/arob35/Sites/nike/ashpod/node_modules/aurelia-webpack-plugin/index.js:25:35
    at Array.forEach (native)
    at getContextMap (/Users/arob35/Sites/nike/ashpod/node_modules/aurelia-webpack-plugin/index.js:15:18)
    at AureliaWebpackPlugin.<anonymous> (/Users/arob35/Sites/nike/ashpod/node_modules/aurelia-webpack-plugin/index.js:59:29)
    at /Users/arob35/Sites/nike/ashpod/node_modules/aurelia-webpack-plugin/index.js:93:7
    at /Users/arob35/Sites/nike/ashpod/node_modules/webpack/lib/ContextModuleFactory.js:124:5
    at /Users/arob35/Sites/nike/ashpod/node_modules/async/lib/async.js:52:16
    at /Users/arob35/Sites/nike/ashpod/node_modules/async/lib/async.js:361:13
```

**Comment by aaronroberson** [comment]
This is also happening with log4js v0.6.35. The current workaround is to add the packages to devDependencies.

**Comment by Vheissu** [comment]
The later releases of the plugin from the last week or so (especially today's release 1.0.0-beta.4.0.0) change how packages are resolved, so this aforementioned issue should no longer be a problem.
