### ISSUE TITLE
Replacement for includeSubModules in new version?

### ISSUE THREAD

**Issue by Zensavona** [aurelia/webpack-plugin#48]
Hi guys, I just updated to the latest version of `aurelia-webpack-plugin` (`1.0.0-beta.4.0.0`) and I'm having some difficulty understanding the new `package.json` config options...

Previously I used a config in the `webpack.config.js` like this:

```
plugins: [
    new AureliaWebpackPlugin({
      includeSubModules: [
        { moduleId: 'aurelia-validation' },
        { moduleId: 'aurelia-dialog' },
      ],
    }),
...
```

Since upgrading my understanding is that the `includeSubModules` config option is removed, what's the correct way to include these submodules now? I'm getting a console error as below with `aurelia-validation@0.6.7`:

```
Uncaught (in promise) Error: Cannot find module './aurelia-validation/resources/en-US'
```

Or like this with `0.10.0` (which I'd rather not upgrade to just yet anyway as the API is changed):

```
Uncaught (in promise) Error: Cannot find module './aurelia-validation/validate-binding-behavior'
Uncaught (in promise) Error: Cannot find module './aurelia-validation/validation-errors-custom-attribute'
Uncaught (in promise) Error: Cannot find module './aurelia-validation/validation-renderer-custom-attribute'
```

Thanks!

**Comment by mgerwinn** [comment]
for aurelia-i18n adding this to the package.json is working for me:

 ```
 "aurelia": {
    "build": {
      "resources": [
        "aurelia-i18n/t",
        "aurelia-i18n/nf",
        "aurelia-i18n/df",
        "aurelia-i18n/rt"
      ]
    }
  }
```

Maybe you can do something similar with aurelia-validation

**Comment by niieani** [comment]
The packages aurelia-i18n, aurelia-validation and aurelia-dialog haven't yet been updated with the build resources listing in their respectful `package.json` files. We will do so shortly. @mgerwinn is correct about `i18n`, and you may similarly list resources of aurelia-validation and aurelia-dialog directly in your project's `package.json`.

**Comment by Zensavona** [comment]
just for future reference, this is what's needed in `package.json` to make `aurelia-validation` happy:

```
"aurelia": {
    "build": {
      "resources": [
        "aurelia-validation/resources/en-US",
        "aurelia-validation/validate-custom-attribute"
      ]
    }
  },
```

thanks @niieani and @mgerwinn

**Comment by EisenbergEffect** [comment]
@Zensavona Perhaps you would like to submit a PR to that package to fix it for everyone?

**Comment by Zensavona** [comment]
@EisenbergEffect already working on one 😉

**Comment by jdanyow** [comment]
thanks @Zensavona !

**Comment by mdurling** [comment]
I recently had to add "aurelia-templating-resources/attr-binding-behavior" in my package.json's Aurelia build resources to work around an exception in the Webpack resolver. Any idea why this would be? I started getting the exception after I removed my node_modules folder and reran npm install. While I am happy to have figured out a workaround, I am curious to understand what may have happened and why this was necessary. @EisenbergEffect

**Comment by niieani** [comment]
What's the exception you were "working around", @mdurling?

**Comment by mdurling** [comment]
@niieani Here is the exception:

Unhandled rejection Error: Cannot find module './aurelia-templating-resources/attr-binding-behavior'.
    at webpackContextResolve (http://localhost.inmotionnow.com:9000/app.bundle.js:688:9)
    at webpackContext (http://localhost.inmotionnow.com:9000/app.bundle.js:683:29)
    at http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15731:48
From previous event:
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15730:99)
From previous event:
    at WebpackLoader._import (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15716:18)
    at WebpackLoader.loadModule (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15774:17)
    at WebpackLoader.loadAllModules (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15761:23)
    at ViewEngine.importViewResources (http://localhost.inmotionnow.com:9000/aurelia.bundle.js:4808:24)
    at http://localhost.inmotionnow.com:9000/aurelia.bundle.js:14663:23
From previous event:
    at loadResources (http://localhost.inmotionnow.com:9000/aurelia.bundle.js:14654:7)
    at http://localhost.inmotionnow.com:9000/aurelia.bundle.js:14731:14
    at next (http://localhost.inmotionnow.com:9000/aurelia.bundle.js:14611:30)
    at runTasks (http://localhost.inmotionnow.com:9000/aurelia.bundle.js:14617:10)
    at http://localhost.inmotionnow.com:9000/aurelia.bundle.js:14896:16
From previous event:
    at http://localhost.inmotionnow.com:9000/aurelia.bundle.js:14895:21
From previous event:
    at FrameworkConfiguration.apply (http://localhost.inmotionnow.com:9000/aurelia.bundle.js:14880:42)
    at Aurelia.start (http://localhost.inmotionnow.com:9000/aurelia.bundle.js:14497:21)
    at Object._callee$ (http://localhost.inmotionnow.com:9000/app.bundle.js:1484:40)
    at tryCatch (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:8230:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:8504:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:8263:21)
    at http://localhost.inmotionnow.com:9000/app.bundle.js:1466:65
From previous event:
    at __awaiter (http://localhost.inmotionnow.com:9000/app.bundle.js:1446:12)
    at Object.configure (http://localhost.inmotionnow.com:9000/app.bundle.js:1472:12)
    at http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15541:27
From previous event:
    at config (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15540:46)
    at handleApp (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15531:10)
    at http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15559:9
From previous event:
    at http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15556:44
From previous event:
    at run (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15553:24)
    at Object.<anonymous> (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15578:1)
    at Object.aurelia-bootstrapper-webpack (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:15579:30)
    at __webpack_require__ (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:57:38)
    at Object.161 (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:12512:1)
    at __webpack_require__ (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:57:38)
    at 0 (http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:140:18)
    at http://localhost.inmotionnow.com:9000/aurelia-bootstrap.bundle.js:143:10

**Comment by mdurling** [comment]
@niieani And this is what I added to package.json to fix it:

  "aurelia": {
    "build": {
      "resources": [
        "aurelia-templating-resources/attr-binding-behavior"
      ]
    }
  },

**Comment by niieani** [comment]
Looks like that's a bug of aurelia-templating-resources, which is missing `attr-binding-behavior` as a resource in its package.json. Added a PR: https://github.com/aurelia/templating-resources/pull/254
