### ISSUE TITLE
typescript-webpack production build doesn't work

### ISSUE THREAD

**Issue by sivamamidi-REISys** [aurelia/webpack-plugin#82]
I'm submitting a bug report

Aurelia Skeleton Version
skeleton-typescript-webpack

Framework Version:
master

Please tell us about your environment:

Operating System:
Windwos 10

Node Version:
6.9.1

NPM Version:
3.10.8

JSPM OR Webpack AND Version
webpack 2.1.0-beta.27

Browser:
all

Language:
TypeScript 2.1.1

Current behavior:
npm run build
n
npm run build:prod
both of them showing an error while running
bluebird.js:1546 Unhandled rejection TypeError: Cannot read property 'anchorIsContainer' of undefined
at ViewCompiler.compile (http://localhost/test-app/aurelia.bundle.js:2528:104)
at HtmlBehaviorResource.compile (http://localhost/test-app/aurelia.bundle.js:3936:44)
at ViewCompiler._compileElement (http://localhost/test-app/aurelia.bundle.js:2813:38)
at ViewCompiler._compileNode (http://localhost/test-app/aurelia.bundle.js:2551:21)
at ViewCompiler._compileElement (http://localhost/test-app/aurelia.bundle.js:2843:29)
at ViewCompiler._compileNode (http://localhost/test-app/aurelia.bundle.js:2551:21)
at ViewCompiler._compileElement (http://localhost/test-app/aurelia.bundle.js:2843:29)
at ViewCompiler._compileNode (http://localhost/test-app/aurelia.bundle.js:2551:21)
at ViewCompiler._compileElement (http://localhost/test-app/aurelia.bundle.js:2843:29)
at ViewCompiler._compileNode (http://localhost/test-app/aurelia.bundle.js:2551:21)
at ViewCompiler._compileNode (http://localhost/test-app/aurelia.bundle.js:2573:31)
at ViewCompiler.compile (http://localhost/test-app/aurelia.bundle.js:2520:10)

**Comment by EisenbergEffect** [comment]
We're in the process of making major changes to the webpack skeleton. Please use the official releases if you want something that works. Please only use master if you want to help us test new versions. Note that some of this is pending other releases.

**Comment by Alexander-Taran** [comment]
probably fixed by now

**Comment by jods4** [comment]
In any case, `2.0.0-rc.5` plugin is a complete rewrite of the plugin, so there's no code in common with this old issue.

If something doesn't work with the 2.0 code, please file a new issue.
