### ISSUE TITLE
AureliaWebpackPlugin is not a constructor on version 2.0.0-rc.1

### ISSUE THREAD

**Issue by vincentw56** [aurelia/webpack-plugin#93]
**I'm submitting a bug report**

* **Library Version:**
2.0.0-rc.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v7.4.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
webpack 2.2.1

* **Browser:**
NA

* **Language:**
TypeScript 2.2.1

**Current behavior:**
```
TypeError: AureliaWebpackPlugin is not a constructor
    at Object.<anonymous> (\webpack.config.js:242:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireConfig (\node_modules\webpack\bin\convert-argv.js:96:18)
    at \node_modules\webpack\bin\convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (\node_modules\webpack\bin\convert-argv.js:107:15)
    at Object.<anonymous> (\node_modules\webpack\bin\webpack.js:153:40)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Expected/desired behavior:**
I have this in my Webpack.config.js file:

new AureliaWebpackPlugin({
                    src: Path.resolve("./app/src")
                }),

It worked fine in the previous version. As this changed.

**Comment by jods4** [comment]
Version 2.0 is a complete rethinking of our 1.x webpack plugins.

The error you're hitting is because `AureliaWebpackPlugin` does not exist in v2.0 (it's `AureliaPlugin`) and the name change is on purpose because it takes completely different options.

This is still a preview and docs are coming but if you want to try it right now I suggest that you start here:
https://github.com/jods4/aurelia-webpack-build/wiki
